plugins {
    id 'java'
    id 'application'
}

group = 'com.passkit.grpc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def passkitSdkVersion = '1.1.160'
// Be careful to match grpc versions with netty.
// See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
def grpcVersion = '1.83.1'
def nettyTcNativeVersion = '2.0.83.Final'

test {
    useJUnit()
    maxHeapSize = '1G'
    testLogging {
        outputs.upToDateWhen {false}
        showStandardStreams = true
    }
}

dependencies {
    implementation "com.passkit.grpc:sdk:${passkitSdkVersion}"
    implementation "io.grpc:grpc-all:${grpcVersion}"
    implementation "io.grpc:grpc-netty:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "io.grpc:grpc-testing:${grpcVersion}"
    runtimeOnly "io.netty:netty-tcnative-boringssl-static:${nettyTcNativeVersion}"
    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'com.passkit.quickstart.Main'
}
